@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Main{
  +{static} main(args: String[*])
}

package typeCarte{
    abstract class Carte <<abstract>>
    {
        - m_nom : String
        - m_pointAttaque : Integer
        - m_pointDeVie : Integer
        - m_gouttesDeSang : Integer
        - m_os : Integer
        - m_volant : Boolean
        + <<Create>> Carte(nom : String, PV : Integer)
        + <<Create>> Carte(nom : String, pointAttaque : Integer, PV : Integer, gouttesDeSang : Integer, os : Integer, volant : Boolean)
        + attaquer(other : Animal)
        + getNom() : String
        + getPV() : Integer
        + getAttaque() : Integer
        + getGouttesSang() : Integer
        + getOs() : Integer
        + getVolant() : Boolean
        + isSacrifiable() : Boolean
        + toString() : String
    }
    abstract class Animal extends Carte{
        +<<Create>> Animal(nom : String, pointAttaque : Integer, PV : Integer, gouttesDeSang : Integer, os : Integer, volant : Boolean)
        + isSacrifiable() : Boolean
    }
    abstract class Obstacle extends Carte{
        + <<Create>> Obstacle(PV : Integer, nom : String)
    }
}

package pouvoirs{
    enum Pouvoir <<enumerate>>{
        NOMBREUSES_VIES
        CROISSANCE
        PUANT
        COUREUR
        CONTACT_MORTEL
        PIQUES_POINTUES
    }
}
package factory{
    class CarteFactory{
        +{static} createChat() : Animal
        +{static} createGrizzly() : Animal
        +{static} createCoyote() : Animal
        +{static} createMoineau() : Animal
        +{static} createCorbeau() : Animal
        +{static} createEcureuil() : Animal
        +{static} createHermine() : Animal
        +{static} createLouveteau() : Animal
        +{static} createLoup() : Animal
        +{static} createPunaise() : Animal
        +{static} createRocher() : Obstacle
        +{static} createSapin() : Obstacle
    }
}

package gameplay{
    package jeu{
        class Jeu {
            + <<Create>> Jeu()
            + demarrerJeu()
        }

        class Partie{
            -m_differenceScore : Integer
            -numeroPartie : Integer
            +<<Create>> Partie(numPartie : Integer)
            + demarrerPartie() : String
            + choixCartePioche()
            + toString() : String
        }

        class Joueur{
            - m_scoreJoueur : Integer
            - m_os : Integer
            +<<Create>> Joueur()
            + getScoreJoueur() : Integer
            + getPlateau()
            + getMain()
            + getOs() : Integer
            + piocher()
            + getSizePioche() : Integer
            + poserCarte(carte : Carte, cellule : Integer)
            + poserCarteOs(carte : Animal) : Boolean
            + poserCarteSang(carte : Animal) : Boolean
            + sacrificeCarte(carte : Animal, nbCarteASacrifier : Integer, sacrificeRestant : Integer) : Integer
            + attaquer(autre : Joueur)
            + toString() : String
        }

        class Robot extends Joueur{
            +<<Create>> Robot()
            + jouerTour()
            + tourProchain()
            + poserCarteRobot(carte : Animal, cellule : Integer) : Boolean
            + osRobot : Boolean
            + sacrificeRobot(carte : Animal) : Boolean
            + toString() : String
        }


        class Pioche{
            +<<Create>> Pioche (player : Joueur)
            + initPioche()
            + getTaillePioche() : Integer
            + getPioche()
            + piocher()
            + toString()
        }

    }

    package affichage{
        class Affichage{
            +{static} afficherPlateau()
            +{static} afficherMain()
        }

    }
}

Main .> gameplay.jeu.Jeu : <<use>>
gameplay.jeu.Joueur ..> factory.CarteFactory : <<use>>

Jeu .> Partie : <<use>>

Partie .> Joueur : <<use>>
Partie .> Animal : <<use>>
Partie .> CarteFactory : <<use>>

Affichage .> typeCarte.Carte : "<<use>>"
Affichage .> typeCarte.Animal : "<<use>>"

Animal .> Pouvoir : <<use>>

Carte *--> "1,2" Pouvoir : m_pouvoir

Robot o--> "1" Joueur : m_other

Joueur *--> "1" typeCarte.Animal : m_pioche\nm_mainJoueur
Joueur *--> "1" typeCarte.Carte : m_plateau

Pioche *--> "0..*" Animal : m_pioche
Pioche o--> "1" Joueur : m_joueur

@enduml